Style/IndentationWidth:
    Width: 4

Style/StringLiterals:
    EnforcedStyle: double_quotes

Style/WordArray:
    Enabled: false

Style/GlobalVars:
    AllowedVariables:
        - $Question

Metrics/LineLength:
    Max: 100

AllCops:
    Exclude:
        - "bin/computing-arithmetic-quiz"
        - "vendor/**/*"
