language: ruby
# Travis consults .ruby-version etc.
env:
    global:
        - RACK_ENV=test
        - secure: "HJRKFsO/3RYF149fYfm2OehFZbKWPZ9V/ERoFidFlk2gFhqX/XjbLdg+CROL19z4+vdXqfEhY2E4eZrshh7SQl452c7ls6anPtPz6mcIbf5VQhRPK7bz1pPPQsaAQNwSIh9dCwke1R2a/Qs05ZFHpeUQMaUQ5AHaPHs+RxaXxdI="
        - secure: "jkGMkbg3Wg9uWDb5xV4+vrLZN8slOBNwfzIkg+km7th6ueImQOFau7UrLYBtuPQiT3F3mDqNtcc3jNcTkOS+YwtiIjSfNhfg12Cb3BkIuAYIvZOQ9wvhW+9MqrEeyzRD5lNk2MA88G4/Hb7jbedbaqcd607dDFUP4IW20xBK9so="

script:
    - bundle exec rubocop --format fuubar
    - shopt -s globstar && ruby -wc **/*.rb
    - bundle exec rake test_coverage

sudo: false
cache: bundler
